### ISSUE TITLE
reverse-engineering page is invalid *doesn't' use proper SSL *

### ISSUE THREAD

**Issue by SoffiMeower** [obhq/reverse-engineering#3]

**Comment by ultimaweapon** [comment]
It seems like you enable CloudFlare protection on the obliteration.net. If yes you need to disable this feature to let the DNS point to GitHub servers instead of CloudFlare servers.

**Comment by SoffiMeower** [comment]
> It seems like you enable CloudFlare protection on the obliteration.net. If yes you need to disable this feature to let the DNS point to GitHub servers instead of CloudFlare servers.

Ahaha, no? I mean, the website repo displays just fine, this repo just... Isn't setup right.

**Comment by ultimaweapon** [comment]
I don't know how CloudFlare validates the certificate of the site they are proxied. The easy way to fix this is disabled CloudFlare proxy so the traffic will go to GitHub directly. No reason to use CloudFlare protection here because the destination server is GitHub, not your server.

**Comment by SoffiMeower** [comment]
I fixed it, using Full instead of Full Strict worked :P
